version: '3.8'

services:
  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: coconut-beach-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/restaurant_db?schema=public
      - REDIS_URL=redis://redis:6379
      - TZ=Asia/Bangkok
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_RESTAURANT_NAME=Coconut Beach
      - NEXT_PUBLIC_RESTAURANT_CURRENCY=฿
      - NEXT_PUBLIC_RESTAURANT_WHATSAPP=66812345678
      - NEXTAUTH_SECRET=development-secret-key-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
    networks:
      - coconut-network
    restart: unless-stopped
    command: sh -c "npx prisma generate && npx prisma migrate dev --name init && npm run dev"

  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    container_name: coconut-beach-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - coconut-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: coconut-beach-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - coconut-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer for database management (optional)
  adminer:
    image: adminer
    container_name: coconut-beach-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - coconut-network
    restart: unless-stopped

networks:
  coconut-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
