// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabaseTypes';

// Use environment variables - no fallbacks for security
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// Validate environment variables are set
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missingVars = [];
  if (!SUPABASE_URL) missingVars.push('NEXT_PUBLIC_SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missingVars.push('NEXT_PUBLIC_SUPABASE_ANON_KEY');

  throw new Error(
    `Missing required environment variables: ${missingVars.join(', ')}\n` +
    `Please set these in your Vercel project settings:\n` +
    `1. Go to your Vercel project dashboard\n` +
    `2. Navigate to Settings > Environment Variables\n` +
    `3. Add the following variables:\n` +
    `   - NEXT_PUBLIC_SUPABASE_URL\n` +
    `   - NEXT_PUBLIC_SUPABASE_ANON_KEY\n` +
    `See .env.local.example for reference values.`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom storage adapter that migrates from cookies to localStorage
const customStorage = typeof window !== 'undefined' ? {
  getItem: (key: string) => {
    // First try localStorage (new method)
    const localStorageValue = window.localStorage.getItem(key);
    if (localStorageValue) {
      return localStorageValue;
    }
    
    // Fallback to cookies for migration (old method)
    const cookieValue = document.cookie
      .split('; ')
      .find(row => row.startsWith(key + '='))
      ?.split('=')[1];
    
    // If found in cookies, migrate to localStorage
    if (cookieValue) {
      window.localStorage.setItem(key, cookieValue);
      // Clear the cookie after migration
      document.cookie = `${key}=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT`;
      return cookieValue;
    }
    
    return null;
  },
  setItem: (key: string, value: string) => {
    // Always use localStorage for new values
    window.localStorage.setItem(key, value);
    // Also clear any existing cookies with the same key
    document.cookie = `${key}=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT`;
  },
  removeItem: (key: string) => {
    window.localStorage.removeItem(key);
    // Also clear from cookies
    document.cookie = `${key}=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT`;
  },
} : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Enable automatic session refresh
    autoRefreshToken: true,
    // Persist auth session in localStorage to prevent cookie bloat
    persistSession: true,
    // Detect session in URL (for OAuth flows)
    detectSessionInUrl: true,
    // Storage key for session
    storageKey: 'supabase.auth.token',
    // Use custom storage that migrates from cookies to localStorage
    storage: customStorage,
  },
  realtime: {
    connect: true,
    params: { eventsPerSecond: 10 },
    retryAttempts: 6,
    timeout: 40000
  }
});
