// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabaseTypes';

// Use environment variables - no fallbacks for security
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// During build time or when env vars are missing, use placeholder values
// The EnvConfigValidator component will show a user-friendly error page if needed
const url = SUPABASE_URL || 'https://placeholder.supabase.co';
const key = SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom storage adapter that migrates from cookies to localStorage
const customStorage = typeof window !== 'undefined' ? {
  getItem: (key: string) => {
    // First try localStorage (new method)
    const localStorageValue = window.localStorage.getItem(key);
    if (localStorageValue) {
      return localStorageValue;
    }
    
    // Fallback to cookies for migration (old method)
    const cookieValue = document.cookie
      .split('; ')
      .find(row => row.startsWith(key + '='))
      ?.split('=')[1];
    
    // If found in cookies, migrate to localStorage
    if (cookieValue) {
      window.localStorage.setItem(key, cookieValue);
      // Clear the cookie after migration
      document.cookie = `${key}=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT`;
      return cookieValue;
    }
    
    return null;
  },
  setItem: (key: string, value: string) => {
    // Always use localStorage for new values
    window.localStorage.setItem(key, value);
    // Also clear any existing cookies with the same key
    document.cookie = `${key}=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT`;
  },
  removeItem: (key: string) => {
    window.localStorage.removeItem(key);
    // Also clear from cookies
    document.cookie = `${key}=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT`;
  },
} : undefined;

export const supabase = createClient<Database>(url, key, {
  auth: {
    // Enable automatic session refresh
    autoRefreshToken: true,
    // Persist auth session in localStorage to prevent cookie bloat
    persistSession: true,
    // Detect session in URL (for OAuth flows)
    detectSessionInUrl: true,
    // Storage key for session
    storageKey: 'supabase.auth.token',
    // Use custom storage that migrates from cookies to localStorage
    storage: customStorage,
  },
  realtime: {
    connect: true,
    params: { eventsPerSecond: 10 },
    retryAttempts: 6,
    timeout: 40000
  }
});
